## Functions

# Conjugate

+⟨1,2,3⟩

# Add

5+⟨1,2,3⟩

# Negate

-⟨1,2,3,4⟩

# Subtract

"abcd"-32

# Not

¬⟨0,1,0.25,0.75⟩

# Span

15¬10
9¬7
1¬3

# Absolute Value

|⟨¯3,0,4⟩

# Modulus

3|↕8

# Enclose

<"abc"

# Less Than

5<↕9

# Merge

"see Solo and Couple first"

# Greater Than

5>↕9
⟨@,'a','Z'⟩>∞

# Greater Than or Equal to

5≥↕9

# Rank

=44
=↕4
=⟨⟩
=2‿2⥊↕4
=2‿3‿4⥊↕24
=⟨1‿2,3‿4‿5⟩

# Equals

'e'="Mesmerize"

# Reshape

2‿3‿4⥊↕24

## Modifiers

# Fold

⋈´"abcde"
-´⟨1,2,3,4⟩
+´⟨⟩
⌊´⟨⟩
100-´⟨1,2,3,4⟩

# Scan

-`⟨1,2,3,4⟩
100-`⟨1,2,3,4⟩
