## Functions

# Conjugate

+⟨1,2,3⟩

# Add

5+⟨1,2,3⟩

# Negate

-⟨1,2,3,4⟩

# Subtract

"abcd"-32

# Sign

×⟨¯3,¯2,¯1,0,1,2,3⟩

# Multiply

×˜1+↕4

# Reciprocal

# Divide

# Exponential

# Power

# Square Root

# Root

# Floor

# Minimum

# Ceiling

# Maximum

# Sort Up

# And

# Sort Down

# Or

# Not

¬⟨0,1,0.25,0.75⟩

# Span

15¬10
9¬7
1¬3

# Absolute Value

|⟨¯3,0,4⟩

# Modulus

3|↕8

# Less Than or Equal to

# Enclose

<"abc"

# Less Than

5<↕9

# Merge

"first do Solo and Couple"

# Greater Than

5>↕9
⟨@,'a','Z'⟩>∞

# Greater Than or Equal to

5≥↕9

# Rank

=44
=↕4
=⟨⟩
=2‿2⥊↕4
=2‿3‿4⥊↕24
=⟨1‿2,3‿4‿5⟩

# Equals

'e'="Mesmerize"

# Length

# Not Equals

# Depth

# Match

# Shape

# Not Match

# Identity

# Left

# Right

# Deshape

⥊2‿3‿4⥊↕24
⥊⟨1,⟨2,3,⟨4,5⟩⟩⟩

# Reshape

2‿3‿4⥊↕24

# Join

# Join to

# Solo

# Couple

# Enlist

# Pair

# Prefixes

# Take

# Suffixes

# Drop

# Range

# Windows

# Nudge

# Shift Before

# Nudge Back

# Shift After

# Reverse

# Rotate

# Transpose

# Reorder Axes

# Indices

# Replicate

# Grade Up

# Bins Up

# Grade Down

# Bins Down

# First Cell

# Select

# First

# Pick

# Classify

# Index of

# Occurrence Count

# Progressive Index of

# Mark Firsts

# Member of

# Deduplicate

# Find

# Group Indices

# Group

# Assert

# Assert with Message

## Modifiers - Combinators

# Constant

# Self/Swap

# Atop

# Over

# Before/Bind

# After/Bind

# Valences

# Choose

# Under

# Catch

## Modifiers - Other

# Cells

# Rank

# Each

# Depth

# Table

# Undo

# Repeat

# Fold

⋈´"abcde"
-´⟨1,2,3,4⟩
+´⟨⟩
⌊´⟨⟩
100-´⟨1,2,3,4⟩

# Insert

# Scan

# Scan

-`⟨1,2,3,4⟩
100-`⟨1,2,3,4⟩
